namespace App\Domains\Manager\Horaireagents;

class HoraireagentsShowDeleteIhmDto
{
    public $Id="";
    public $HoraireId="";
    public $UserId="";
    public $Lun="";
    public $Mar="";
    public $Mer="";
    public $Jeu="";
    public $Ven="";
    public $Sam="";
    public $Dim="";
    public $CreatedAt="";
    public $UpdatedAt="";
    public $ExtraAttributes="";
    public $DeletedAt="";
    public $IdentifiantsSadge="";
    public $CreatBy="";
    public $Typesagents="";
    public $Horaires=[];
    public $Users=[];
    public $Postes=[];
    public $Balises=[];
    public $Categories=[];
    public $Contrats=[];
    public $Directions=[];
    public $Echelons=[];
    public $Fonctions=[];
    public $Matrimoniales=[];
    public $Nationalites=[];
    public $Roles=[];
    public $Sexes=[];
    public $Sites=[];
    public $Situations=[];
    public $Typeseffectifs=[];
    public $Villes=[];
    public $Zones=[];
    public $Contratsclients=[];
    public $Postesarticles=[];
    public $Typespostes=[];
    public $Services=[];
    public $Clients=[];
    public $Pointeuses=[];
    public $Typessites=[];
    public $Provinces=[];

}
