class UserszonesReadDataDto
{
    String Id="";
    String UserId="";
    String ZoneId="";
    String CreatedAt="";
    String UpdatedAt="";
    String DeletedAt="";
    String ExtraAttributes="";
    String IdentifiantsSadge="";
    String CreatBy="";
    String DatabaseHost="";
    String DatabasePass="";
    String DatabaseName="";
    String DatabaseUser="";
    String ApiLink="";
    List Users=[];
    List Zones=[];
    List Balises=[];
    List Categories=[];
    List Contrats=[];
    List Directions=[];
    List Echelons=[];
    List Fonctions=[];
    List Matrimoniales=[];
    List Nationalites=[];
    List Postes=[];
    List Roles=[];
    List Sexes=[];
    List Sites=[];
    List Situations=[];
    List Typeseffectifs=[];
    List Villes=[];
    List Provinces=[];
    List Services=[];
    List Contratsclients=[];
    List Postesarticles=[];
    List Typespostes=[];
    List Clients=[];
    List Pointeuses=[];
    List Typessites=[];

}
