class PostesDeleteDataDto
{
    String Id="";
    String Code="";
    String Libelle="";
    String Nature="";
    String Coordonnees="";
    String SiteId="";
    String CreatedAt="";
    String UpdatedAt="";
    String ExtraAttributes="";
    String DeletedAt="";
    String IdentifiantsSadge="";
    String CreatBy="";
    String Jours="";
    String ContratsclientId="";
    String Maxjours="";
    String Maxnuits="";
    String NbrsJours="";
    String NbrsNuits="";
    String IsCouvert="";
    String Pointeuses="";
    String Agentjour="";
    String Agentnuit="";
    String CouvertAgentjour="";
    String CouvertAgentnuit="";
    String Type="";
    String Typeagents="";
    String TypesposteId="";
    String PostesarticleId="";
    String StatusComplets="";
    String DbHost="";
    String DbPass="";
    String DbName="";
    String DbUser="";
    String ApiLink="";
    List Contratsclients=[];
    List Postesarticles=[];
    List Sites=[];
    List Typespostes=[];
    List Clients=[];
    List Pointeuses=[];
    List Typessites=[];
    List Zones=[];
    List Provinces=[];
    List Villes=[];

}
