namespace App\Domains\Manager\Preuves;

class PreuvesShowUpdateIhmDto
{
    public $Id="";
    public $ProgrammeId="";
    public $TransactionId="";
    public $PunchTime="";
    public $Type="";
    public $Role="";
    public $Etats="";
    public $ExtraAttributes="";
    public $CreatedAt="";
    public $UpdatedAt="";
    public $DeletedAt="";
    public $IdentifiantsSadge="";
    public $CreatBy="";
    public $Valide="";
    public $Remarque="";
    public $Programmes=[];
    public $Transactions=[];
    public $Horaires=[];
    public $Postes=[];
    public $Programmations=[];
    public $Typesheures=[];
    public $Users=[];
    public $Balises=[];
    public $Cartes=[];
    public $Clients=[];
    public $Controlleursacces=[];
    public $Echelons=[];
    public $Fonctions=[];
    public $Identifications=[];
    public $Lignes=[];
    public $Matrimoniales=[];
    public $Pointeuses=[];
    public $Sexes=[];
    public $Sites=[];
    public $Situations=[];
    public $Villes=[];
    public $Zones=[];
    public $Contratsclients=[];
    public $Postesarticles=[];
    public $Typespostes=[];
    public $Categories=[];
    public $Contrats=[];
    public $Directions=[];
    public $Nationalites=[];
    public $Roles=[];
    public $Typeseffectifs=[];
    public $Deplacements=[];
    public $Services=[];
    public $Typessites=[];
    public $Provinces=[];
    public $Lignesmoyenstransports=[];
    public $Moyenstransports=[];
    public $Typesmoyenstransports=[];

}
